import { describe, it, expect } from "vitest";
import { generateTemplateHtml } from "../template";

describe("template utils", () => {
  describe("generateTemplateHtml", () => {
    it("should generate valid HTML with form and auto-submit script", () => {
      const html = generateTemplateHtml("test-template", {
        "index.js": "console.log('hello');",
      });

      expect(html).toContain('<html lang="en">');
      expect(html).toContain('<form id="mainForm"');
      expect(html).toContain('method="post"');
      expect(html).toContain('action="https://khulnasoft.com/run"');
      expect(html).toContain('<script>document.getElementById("mainForm").submit();</script>');
    });

    it("should include project title in hidden input", () => {
      const name = "my-awesome-template";
      const html = generateTemplateHtml(name, {});

      expect(html).toContain(`name="project[title]" value="${name}"`);
    });

    it("should include project description", () => {
      const html = generateTemplateHtml("test", {});

      expect(html).toContain('name="project[description]"');
      expect(html).toContain('value="generated by https://pkg.khulnasoft.com"');
    });

    it("should set template type to node", () => {
      const html = generateTemplateHtml("test", {});

      expect(html).toContain('name="project[template]" value="node"');
    });

    it("should include all files with escaped content", () => {
      const files = {
        "index.js": "console.log('test');",
        "package.json": '{"name": "test"}',
        "README.md": "# Test Project",
      };

      const html = generateTemplateHtml("test", files);

      expect(html).toContain('name="project[files][index.js]"');
      expect(html).toContain('name="project[files][package.json]"');
      expect(html).toContain('name="project[files][README.md]"');
    });

    it("should escape HTML special characters in file content", () => {
      const files = {
        "index.html": '<div class="test" id="main">Hello & goodbye</div>',
      };

      const html = generateTemplateHtml("test", files);

      expect(html).toContain("&lt;div");
      expect(html).toContain("&quot;test&quot;");
      expect(html).toContain("&amp;");
      expect(html).toContain("&gt;");
    });

    it("should escape square brackets in filenames", () => {
      const files = {
        "src/[id].js": "export default function() {}",
      };

      const html = generateTemplateHtml("test", files);

      expect(html).toContain("%5Bid%5D");
      expect(html).not.toContain("[id]");
    });

    it("should handle empty files object", () => {
      const html = generateTemplateHtml("empty-template", {});

      expect(html).toContain('<form id="mainForm"');
      expect(html).toContain('value="empty-template"');
    });

    it("should handle files with quotes in content", () => {
      const files = {
        "test.js": `const str = "hello"; const str2 = 'world';`,
      };

      const html = generateTemplateHtml("test", files);

      expect(html).toContain("&quot;hello&quot;");
      expect(html).toContain("&#39;world&#39;");
    });

    it("should handle files with mixed special characters", () => {
      const files = {
        "config.xml": '<config attr="value" id=\'test\'>&amp;</config>',
      };

      const html = generateTemplateHtml("test", files);

      expect(html).toContain("&lt;config");
      expect(html).toContain("&quot;value&quot;");
      expect(html).toContain("&#39;test&#39;");
      expect(html).toContain("&amp;amp;");
    });

    it("should handle nested directory paths", () => {
      const files = {
        "src/components/Button.jsx": "export default Button;",
        "src/utils/helpers.js": "export function help() {}",
      };

      const html = generateTemplateHtml("test", files);

      expect(html).toContain("src/components/Button.jsx");
      expect(html).toContain("src/utils/helpers.js");
    });

    it("should handle special filename characters correctly", () => {
      const files = {
        "file[with]brackets.js": "code",
        "normal-file.js": "code",
      };

      const html = generateTemplateHtml("test", files);

      expect(html).toContain("file%5Bwith%5Dbrackets.js");
      expect(html).toContain("normal-file.js");
    });

    it("should produce valid HTML structure", () => {
      const html = generateTemplateHtml("test", { "index.js": "test" });

      // Check basic HTML structure
      expect(html.match(/<html/g)?.length).toBe(1);
      expect(html.match(/<\/html>/g)?.length).toBe(1);
      expect(html.match(/<head/g)?.length).toBe(1);
      expect(html.match(/<\/head>/g)?.length).toBe(1);
      expect(html.match(/<body/g)?.length).toBe(1);
      expect(html.match(/<\/body>/g)?.length).toBe(1);
      expect(html.match(/<form/g)?.length).toBe(1);
      expect(html.match(/<\/form>/g)?.length).toBe(1);
    });
  });
});