import { describe, it, expect } from "vitest";
import { generateTemplateHtml } from "../template.js";

describe("template utils", () => {
  describe("generateTemplateHtml", () => {
    it("should generate valid HTML with basic files", () => {
      const files = {
        "index.js": "console.log('hello');",
        "package.json": '{"name":"test"}',
      };
      
      const html = generateTemplateHtml("test-template", files);
      
      expect(html).toContain("<html");
      expect(html).toContain("</html>");
      expect(html).toContain("<form");
      expect(html).toContain('method="post"');
      expect(html).toContain('action="https://stackblitz.com/run"');
    });

    it("should include all files as hidden inputs", () => {
      const files = {
        "index.js": "const x = 1;",
        "README.md": "# Test",
        "package.json": "{}",
      };
      
      const html = generateTemplateHtml("test", files);
      
      expect(html).toContain('name="project[files][index.js]"');
      expect(html).toContain('name="project[files][README.md]"');
      expect(html).toContain('name="project[files][package.json]"');
    });

    it("should escape HTML special characters in file content", () => {
      const files = {
        "test.js": '<script>alert("xss")</script>',
      };
      
      const html = generateTemplateHtml("test", files);
      
      expect(html).toContain("&lt;script&gt;");
      expect(html).toContain("&quot;");
      expect(html).not.toContain('<script>alert("xss")</script>');
    });

    it("should escape ampersands in file content", () => {
      const files = {
        "test.js": "const x = a && b;",
      };
      
      const html = generateTemplateHtml("test", files);
      
      expect(html).toContain("&amp;&amp;");
    });

    it("should escape single quotes in file content", () => {
      const files = {
        "test.js": "const str = 'hello';",
      };
      
      const html = generateTemplateHtml("test", files);
      
      expect(html).toContain("&#39;");
    });

    it("should escape brackets in filenames", () => {
      const files = {
        "[slug].js": "export default {}",
      };
      
      const html = generateTemplateHtml("test", files);
      
      expect(html).toContain("%5Bslug%5D.js");
      expect(html).not.toContain('name="project[files][[slug].js]"');
    });

    it("should handle nested directory paths", () => {
      const files = {
        "src/components/Button.js": "export const Button = () => {};",
      };
      
      const html = generateTemplateHtml("test", files);
      
      expect(html).toContain('name="project[files][src/components/Button.js]"');
    });

    it("should set correct project metadata", () => {
      const html = generateTemplateHtml("my-project", {});
      
      expect(html).toContain('name="project[title]" value="my-project"');
      expect(html).toContain('name="project[template]" value="node"');
      expect(html).toContain('name="project[description]" value="generated by https://pkg.khulnasoft.com"');
    });

    it("should include auto-submit script", () => {
      const html = generateTemplateHtml("test", {});
      
      expect(html).toContain("<script>");
      expect(html).toContain('.submit()');
    });

    it("should handle empty file content", () => {
      const files = {
        "empty.js": "",
      };
      
      const html = generateTemplateHtml("test", files);
      
      expect(html).toContain('name="project[files][empty.js]"');
      expect(html).toContain('value=""');
    });

    it("should handle files with newlines", () => {
      const files = {
        "multi.js": "line1\nline2\nline3",
      };
      
      const html = generateTemplateHtml("test", files);
      
      expect(html).toContain("line1");
      expect(html).toContain("line2");
      expect(html).toContain("line3");
    });

    it("should handle multiple special characters together", () => {
      const files = {
        "test.js": `const x = "<div class='test' data-value=\"123\">Hello & goodbye</div>";`,
      };
      
      const html = generateTemplateHtml("test", files);
      
      expect(html).toContain("&lt;div");
      expect(html).toContain("&#39;test&#39;");
      expect(html).toContain("&quot;123&quot;");
      expect(html).toContain("&amp;");
      expect(html).toContain("&gt;");
    });

    it("should handle greater than and less than symbols", () => {
      const files = {
        "test.js": "const result = a > b && c < d;",
      };
      
      const html = generateTemplateHtml("test", files);
      
      expect(html).toContain("&gt;");
      expect(html).toContain("&lt;");
    });

    it("should not double-escape already safe content", () => {
      const files = {
        "safe.js": "const x = 123;",
      };
      
      const html = generateTemplateHtml("test", files);
      
      expect(html).not.toContain("&amp;amp;");
    });

    it("should handle Unicode characters", () => {
      const files = {
        "unicode.js": "const emoji = '🚀';",
      };
      
      const html = generateTemplateHtml("test", files);
      
      expect(html).toContain("🚀");
    });

    it("should handle files with various extensions", () => {
      const files = {
        "index.html": "<html></html>",
        "style.css": "body { margin: 0; }",
        "script.ts": "const x: number = 1;",
        "data.json": '{"key": "value"}',
      };
      
      const html = generateTemplateHtml("test", files);
      
      Object.keys(files).forEach((filename) => {
        expect(html).toContain(`name="project[files][${filename}]"`);
      });
    });

    it("should escape filenames with special characters", () => {
      const files = {
        "[id].tsx": "export default () => null;",
        "test[123].js": "console.log();",
      };
      
      const html = generateTemplateHtml("test", files);
      
      expect(html).toContain("%5Bid%5D.tsx");
      expect(html).toContain("test%5B123%5D.js");
    });

    it("should preserve spaces in filenames", () => {
      const files = {
        "my file.js": "const x = 1;",
      };
      
      const html = generateTemplateHtml("test", files);
      
      expect(html).toContain('name="project[files][my file.js]"');
    });

    it("should handle large file content", () => {
      const largeContent = "a".repeat(10000);
      const files = {
        "large.js": largeContent,
      };
      
      const html = generateTemplateHtml("test", files);
      
      expect(html).toContain(largeContent);
    });

    it("should create form targeting _self", () => {
      const html = generateTemplateHtml("test", {});
      
      expect(html).toContain('target="_self"');
    });

    it("should have form with id mainForm", () => {
      const html = generateTemplateHtml("test", {});
      
      expect(html).toContain('id="mainForm"');
    });
  });
});