import { describe, it, expect } from "vitest";
import { createDefaultTemplate } from "../template";

describe("CLI template", () => {
  describe("createDefaultTemplate", () => {
    it("should create template with provided dependencies", () => {
      const deps = {
        "package-a": "https://pkg.khulnasoft.com/org/repo/package-a@abc123",
        "package-b": "https://pkg.khulnasoft.com/org/repo/package-b@abc123",
      };

      const template = createDefaultTemplate(deps);

      expect(template).toHaveProperty("index.js");
      expect(template).toHaveProperty("README.md");
      expect(template).toHaveProperty("package.json");
    });

    it("should include empty index.js", () => {
      const template = createDefaultTemplate({});

      expect(template["index.js"]).toBe("");
    });

    it("should include README.md with instructions", () => {
      const deps = {
        "my-package": "https://pkg.khulnasoft.com/org/repo/my-package@abc123",
      };

      const template = createDefaultTemplate(deps);
      const readme = template["README.md"];

      expect(readme).toContain("# Default Template");
      expect(readme).toContain("pkg.khulnasoft.com");
      expect(readme).toContain("npm i");
      expect(readme).toContain("https://pkg.khulnasoft.com/org/repo/my-package@abc123");
    });

    it("should include all dependency URLs in README", () => {
      const deps = {
        "pkg-a": "https://pkg.khulnasoft.com/org/repo/pkg-a@abc123",
        "pkg-b": "https://pkg.khulnasoft.com/org/repo/pkg-b@def456",
      };

      const template = createDefaultTemplate(deps);
      const readme = template["README.md"];

      expect(readme).toContain("https://pkg.khulnasoft.com/org/repo/pkg-a@abc123");
      expect(readme).toContain("https://pkg.khulnasoft.com/org/repo/pkg-b@def456");
    });

    it("should create valid package.json structure", () => {
      const deps = {
        "my-package": "https://pkg.khulnasoft.com/org/repo/my-package@abc123",
      };

      const template = createDefaultTemplate(deps);
      const packageJson = JSON.parse(template["package.json"]);

      expect(packageJson.name).toBe("default");
      expect(packageJson.version).toBe("1.0.0");
      expect(packageJson.description).toBe("generated by pkg.khulnasoft.com");
      expect(packageJson.main).toBe("index.js");
      expect(packageJson.author).toBe("pkg.khulnasoft.com");
      expect(packageJson.license).toBe("ISC");
    });

    it("should include dependencies in package.json", () => {
      const deps = {
        "pkg-a": "https://pkg.khulnasoft.com/org/repo/pkg-a@abc123",
        "pkg-b": "https://pkg.khulnasoft.com/org/repo/pkg-b@def456",
      };

      const template = createDefaultTemplate(deps);
      const packageJson = JSON.parse(template["package.json"]);

      expect(packageJson.dependencies).toEqual(deps);
    });

    it("should handle empty dependencies", () => {
      const template = createDefaultTemplate({});
      const packageJson = JSON.parse(template["package.json"]);

      expect(packageJson.dependencies).toEqual({});
    });

    it("should format package.json with 2-space indentation", () => {
      const template = createDefaultTemplate({ test: "url" });
      const packageJsonStr = template["package.json"];

      // Check for 2-space indentation
      expect(packageJsonStr).toContain('  "name"');
      expect(packageJsonStr).toContain('  "version"');
      expect(packageJsonStr).not.toContain('    "name"');
    });

    it("should contain template usage instructions", () => {
      const template = createDefaultTemplate({});
      const readme = template["README.md"];

      expect(readme).toContain("## Usage");
      expect(readme).toContain("npx pkg-khulnasoft publish");
      expect(readme).toContain("--template");
    });

    it("should mention benefits of the feature", () => {
      const template = createDefaultTemplate({});
      const readme = template["README.md"];

      expect(readme).toContain("## Benefits");
      expect(readme).toContain("Interactive Demos");
      expect(readme).toContain("Enhanced Testing");
      expect(readme).toContain("Improved Sharing");
    });
  });
});