import { describe, it, expect } from "vitest";
import { createDefaultTemplate } from "./template";

describe("Template Generation", () => {
  describe("createDefaultTemplate", () => {
    it("should create template with index.js", () => {
      const dependencies = {
        "package-a": "https://pkg.khulnasoft.com/owner/repo/package-a@abc123",
      };

      const template = createDefaultTemplate(dependencies);

      expect(template["index.js"]).toBeDefined();
      expect(template["index.js"]).toBe("");
    });

    it("should create template with README.md", () => {
      const dependencies = {
        "package-a": "https://pkg.khulnasoft.com/owner/repo/package-a@abc123",
      };

      const template = createDefaultTemplate(dependencies);

      expect(template["README.md"]).toBeDefined();
      expect(template["README.md"]).toContain("Default Template");
      expect(template["README.md"]).toContain("pkg.khulnasoft.com");
    });

    it("should create template with package.json", () => {
      const dependencies = {
        "package-a": "https://pkg.khulnasoft.com/owner/repo/package-a@abc123",
      };

      const template = createDefaultTemplate(dependencies);

      expect(template["package.json"]).toBeDefined();
      
      const packageJson = JSON.parse(template["package.json"]);
      expect(packageJson.name).toBe("default");
      expect(packageJson.version).toBe("1.0.0");
      expect(packageJson.main).toBe("index.js");
    });

    it("should include dependencies in package.json", () => {
      const dependencies = {
        "package-a": "https://pkg.khulnasoft.com/owner/repo/package-a@abc123",
        "package-b": "https://pkg.khulnasoft.com/owner/repo/package-b@def456",
      };

      const template = createDefaultTemplate(dependencies);
      const packageJson = JSON.parse(template["package.json"]);

      expect(packageJson.dependencies).toEqual(dependencies);
      expect(packageJson.dependencies["package-a"]).toBe(dependencies["package-a"]);
      expect(packageJson.dependencies["package-b"]).toBe(dependencies["package-b"]);
    });

    it("should include install commands in README for each dependency", () => {
      const dependencies = {
        "package-a": "https://pkg.khulnasoft.com/owner/repo/package-a@abc123",
        "package-b": "https://pkg.khulnasoft.com/owner/repo/package-b@def456",
      };

      const template = createDefaultTemplate(dependencies);

      expect(template["README.md"]).toContain("npm i");
      expect(template["README.md"]).toContain(dependencies["package-a"]);
      expect(template["README.md"]).toContain(dependencies["package-b"]);
    });

    it("should handle empty dependencies", () => {
      const dependencies = {};

      const template = createDefaultTemplate(dependencies);
      const packageJson = JSON.parse(template["package.json"]);

      expect(packageJson.dependencies).toEqual({});
      expect(Object.keys(template)).toContain("index.js");
      expect(Object.keys(template)).toContain("README.md");
      expect(Object.keys(template)).toContain("package.json");
    });

    it("should handle single dependency", () => {
      const dependencies = {
        "single-package": "https://pkg.khulnasoft.com/owner/repo/single-package@xyz789",
      };

      const template = createDefaultTemplate(dependencies);
      const packageJson = JSON.parse(template["package.json"]);

      expect(Object.keys(packageJson.dependencies)).toHaveLength(1);
      expect(packageJson.dependencies["single-package"]).toBe(dependencies["single-package"]);
    });

    it("should handle scoped package dependencies", () => {
      const dependencies = {
        "@scope/package": "https://pkg.khulnasoft.com/owner/repo/@scope/package@abc123",
      };

      const template = createDefaultTemplate(dependencies);
      const packageJson = JSON.parse(template["package.json"]);

      expect(packageJson.dependencies["@scope/package"]).toBe(dependencies["@scope/package"]);
    });

    it("should set correct package.json metadata", () => {
      const dependencies = {
        "package-a": "https://pkg.khulnasoft.com/owner/repo/package-a@abc123",
      };

      const template = createDefaultTemplate(dependencies);
      const packageJson = JSON.parse(template["package.json"]);

      expect(packageJson.name).toBe("default");
      expect(packageJson.version).toBe("1.0.0");
      expect(packageJson.description).toBe("generated by pkg.khulnasoft.com");
      expect(packageJson.main).toBe("index.js");
      expect(packageJson.author).toBe("pkg.khulnasoft.com");
      expect(packageJson.license).toBe("ISC");
      expect(packageJson.keywords).toEqual([]);
    });

    it("should create exactly three files", () => {
      const dependencies = {
        "package-a": "https://pkg.khulnasoft.com/owner/repo/package-a@abc123",
      };

      const template = createDefaultTemplate(dependencies);
      const files = Object.keys(template);

      expect(files).toHaveLength(3);
      expect(files).toContain("index.js");
      expect(files).toContain("README.md");
      expect(files).toContain("package.json");
    });

    it("should include usage instructions in README", () => {
      const dependencies = {
        "package-a": "https://pkg.khulnasoft.com/owner/repo/package-a@abc123",
      };

      const template = createDefaultTemplate(dependencies);

      expect(template["README.md"]).toContain("## Usage");
      expect(template["README.md"]).toContain("npx pkg-khulnasoft publish");
      expect(template["README.md"]).toContain("--template");
    });

    it("should include benefits section in README", () => {
      const dependencies = {
        "package-a": "https://pkg.khulnasoft.com/owner/repo/package-a@abc123",
      };

      const template = createDefaultTemplate(dependencies);

      expect(template["README.md"]).toContain("## Benefits");
      expect(template["README.md"]).toContain("Interactive Demos");
      expect(template["README.md"]).toContain("Enhanced Testing");
      expect(template["README.md"]).toContain("Improved Sharing");
    });

    it("should format package.json with proper indentation", () => {
      const dependencies = {
        "package-a": "https://pkg.khulnasoft.com/owner/repo/package-a@abc123",
      };

      const template = createDefaultTemplate(dependencies);
      const packageJson = template["package.json"];

      // Check if it's formatted (has newlines and spaces)
      expect(packageJson).toContain("\n");
      expect(packageJson).toContain("  ");
      
      // Should be parseable
      expect(() => JSON.parse(packageJson)).not.toThrow();
    });

    it("should handle multiple dependencies with different URL patterns", () => {
      const dependencies = {
        "short-pkg": "https://pkg.khulnasoft.com/pkg@abc",
        "long-pkg": "https://pkg.khulnasoft.com/owner/repo/long-pkg@def123",
        "@scoped/pkg": "https://pkg.khulnasoft.com/owner/repo/@scoped/pkg@ghi456",
      };

      const template = createDefaultTemplate(dependencies);
      const packageJson = JSON.parse(template["package.json"]);

      expect(Object.keys(packageJson.dependencies)).toHaveLength(3);
      expect(packageJson.dependencies["short-pkg"]).toBe(dependencies["short-pkg"]);
      expect(packageJson.dependencies["long-pkg"]).toBe(dependencies["long-pkg"]);
      expect(packageJson.dependencies["@scoped/pkg"]).toBe(dependencies["@scoped/pkg"]);
    });

    it("should include overview section in README", () => {
      const dependencies = {
        "package-a": "https://pkg.khulnasoft.com/owner/repo/package-a@abc123",
      };

      const template = createDefaultTemplate(dependencies);

      expect(template["README.md"]).toContain("## Overview");
      expect(template["README.md"]).toContain("Templates are particularly useful");
    });

    it("should mention package.json in README", () => {
      const dependencies = {
        "package-a": "https://pkg.khulnasoft.com/owner/repo/package-a@abc123",
      };

      const template = createDefaultTemplate(dependencies);

      expect(template["README.md"]).toContain("package.json");
      expect(template["README.md"]).toContain("generated packages");
    });
  });
});